export const AREA_BRANCH_OPTIONS = {
  A101: [
    "Clh Ampid Branch",
    "Clh Ayala mall Branch",
    "Clh Bayan bayanan Branch",
    "Clh Budgetlane Branch",
    "Clh Condos Branch",
    "Clh Con-Uno Branch",
    "Clh Cupang Bayaga Branch",
    "Clh Double L-L Branch",
    "Clh Dulong bayan Branch",
    "Clh Eastwood Branch",
    "Clh Fairlane Branch",
    "Clh Fortune Branch",
    "Clh Guitnang Bayan Branch",
    "Clh Josef Uno Branch",
    "Clh Kasiglahan Branch",
    "Clh Lamuan Branch",
    "Clh Lilac Branch",
    "Clh Luvers rod Branch",
    "Clh Maly Branch",
    "Clh Marigold Branch",
    "Clh Marikina - 3",
    "Clh Marikina -5 Branch",
    "Clh Marikina -6 Branch",
    "Clh Marikina -7 Branch",
    "Clh Marikina Heights Branch",
    "Clh Marikina-2 Branch",
    "Clh Marquinton Branch",
    "Clh Masinag Branch",
    "Clh Mhbayanan Branch",
    "Clh Modesta Branch",
    "Clh Montalban -1 Branch",
    "Clh Montalban -2 Branch",
    "Clh Mtc Branch",
    "Clh Nangka Branch",
    "Clh Panorama Branch",
    "Clh Parang -2 Branch",
    "Clh Parang -3 Branch",
    "Clh Primark kasiglahan mall Branch",
    "Clh Robinson mall",
    "Clh San isidro Branch",
    "Clh San mateo -1 Branch",
    "Clh San Mateo-2 Branch",
    "Clh San rafael Branch",
    "Clh Soliven Branch",
    "Clh Sta. Lucia building -1 mall Branch",
    "Clh Sta. Lucia Building -3 Branch",
    "Clh Sta. Teresita Branch",
    "Clh Tagumpay Branch",
    "Clh Tumana Branch",
    "Clh Xentro mall Branch",
    "Clh Xrc montana Branch",
  ],
  A102: [
    "CLH BAGBAG NOVA",
    "CLH BAGONG SILANGAN",
    "CLH BANLAT",
    "CLH BATASAN",
    "CLH CAPITOL HILLS DRIVE",
    "CLH COMM 1",
    "CLH COMM 2",
    "CLH COMM 3",
    "CLH CROOSROAD",
    "CLH CULIAT",
    "CLH DAHLIA",
    "CLH DILIMALL",
    "CLH DON ANTONIO",
    "CLH EVER MALL",
    "CLH EXTENSION",
    "CLH FAIRVIEW",
    "CLH FCM",
    "CLH FILINVEST",
    "CLH H- SPIRIT BF.",
    "CLH HILLS DRIVE",
    "CLH JUST JEWEL",
    "CLH KAGAWAD",
    "CLH KATUPARAN",
    "CLH KINGSPOINT",
    "CLH LITEX",
    "CLH LUPANG PANGAKO",
    "CLH LUZON",
    "CLH NORTHFERVIEW",
    "CLH NORTHVIEW",
    "CLH OLD BALARA",
    "CLH OLD CAPITOL",
    "CLH PAYATAS RD.",
    "CLH PH8",
    "CLH RAMAX",
    "CLH REGALADO",
    "CLH REGALADO AVE.",
    "CLH REPUBLIC AVE",
    "CLH RIVERSIDE",
    "CLH SANPEDRO",
    "CLH SAUYO",
    "CLH SAUYO GLOBAL",
    "CLH SOLIVEN",
    "CLH STA LUCIA",
    "CLH TIERRA PURA",
    "CLH TOWNSVILLE",
    "CLH VETERANS",
    "CLH VILLONGCO",
  ],
  A109: [
    "AMANG RODRIGUEZ",
    "AMBERLAND",
    "C RAYMUNDO",
    "CAPITOLYO",
    "CARUNCHO",
    "COUNTRY SIDE",
    "DELA PAZ",
    "DR SIXTO",
    "EJERCITO AVENUE",
    "EVANGELISTA",
    "F. MANALO",
    "FLOODWAY",
    "GREENWOODS",
    "HAGONOY",
    "KARANGALAN",
    "LIFEHOMES",
    "LUZON AVENUE",
    "MARKET AVENUE",
    "MH DEL PILAR",
    "NAGPAYONG",
    "NAPICO",
    "NAPINDAN",
    "PALATIW",
    "PASIG 2",
    "PATEROS 1",
    "PATEROS 2",
    "PINAGBUHATAN",
    "PIONEER",
    "ROSARIO 2",
    "ROSARIO 3",
    "ROTONDA",
    "SAN JOAQUIN",
    "SANTOLAN",
    "SC PASIG",
    "SIGNAL 1",
    "SIGNAL 2",
    "SIGNAL BALLECER",
    "ST. JOSEPH",
    "STA ANA",
    "STELLA MARIZ",
    "TIPAS",
    "TUKTUKAN",
    "WAWA",
  ],
  A110: [
    "AMANG RODRIGUEZ",
    "AMBERLAND",
    "C RAYMUNDO",
    "CAPITOLYO",
    "CARUNCHO",
    "COUNTRY SIDE",
    "DELA PAZ",
    "DR SIXTO",
    "EJERCITO AVENUE",
    "EVANGELISTA",
    "F. MANALO",
    "FLOODWAY",
    "GREENWOODS",
    "HAGONOY",
    "KARANGALAN",
    "LIFEHOMES",
    "LUZON AVENUE",
    "MARKET AVENUE",
    "MH DEL PILAR",
    "NAGPAYONG",
    "NAPICO",
    "NAPINDAN",
    "PALATIW",
    "PASIG 2",
    "PATEROS 1",
    "PATEROS 2",
    "PINAGBUHATAN",
    "PIONEER",
    "ROSARIO 2",
    "ROSARIO 3",
    "ROTONDA",
    "SAN JOAQUIN",
    "SANTOLAN",
    "SC PASIG",
    "SIGNAL 1",
    "SIGNAL 2",
    "SIGNAL BALLECER",
    "ST. JOSEPH",
    "STA ANA",
    "STELLA MARIZ",
    "TIPAS",
    "TUKTUKAN",
    "WAWA",
  ],
  A111: [
    "Clh 88 Square Mall",
    "Clh Admiral",
    "Clh Almanza Uno",
    "Clh Bamboo Organ",
    "Clh BF Almanza",
    "Clh BFRV",
    "Clh BFRV Talon Dos",
    "Clh CAA 1",
    "Clh CAA 2",
    "Clh Casa De Sequoia",
    "Clh ET Homes",
    "Clh Ever",
    "Clh Friendship BFRV",
    "Clh Gooden Acres",
    "Clh LC Casimiro",
    "Clh Marcos Alvarez",
    "Clh Mikesel",
    "Clh Naga Road",
    "Clh One Town Mall",
    "Clh Pamplona",
    "Clh Pamplona Dos",
    "Clh Pilar",
    "Clh Pilar Aguirre",
    "Clh Pulang Lupa",
    "Clh Pulang Lupa Real",
    "Clh Robinsons Mall",
    "Clh SAV 7",
    "Clh Southville",
    "Clh Sta. Cecilia",
    "Clh Talon Tres",
    "Clh Talon Uno",
    "Clh Talon Uno Real",
    "Clh TS Cruz",
    "Clh Tunasan 1",
    "Clh Tunasan 2",
    "Clh Verdant",
    "Clh Zapote Arcade",
  ],
  A113: [
    "AMAIA Steps",
    "BETTER LIVING 1",
    "BETTER LIVING 2",
    "BETTER LIVING 3",
    "BETTERLIVING DON BOSCO",
    "BICUTAN 1",
    "BICUTAN 3",
    "C-5 PHASE-2",
    "C-5 PINAGSAMA",
    "CENTRAL SIGNAL VILLAGE",
    "CENTRAL SIGNAL WATER FUN",
    "CHAMPACA",
    "COMEMB0-1",
    "COMEMBO-2",
    "COMEMBO-3",
    "COMEMBO-4",
    "COMEMBO SAMPALOC",
    "FB - BAYANI ROAD",
    "FB GATE-3",
    "LOWER BICUTAN",
    "MAHARLIKA 1",
    "MAHARLIKA 2",
    "MARKET-MARKET-1",
    "MARKET-MARKET-2",
    "MOONWALK 1",
    "MOONWALK 2",
    "NORTH SIGNAL VILLAGE",
    "PEMBO OSMAK",
    "PEMBO SAMPAGUITA",
    "PEMBO STAFFHOUSE",
    "RIZAL BLUBOZ",
    "SEVERINA",
    "TANYAG",
    "UPPER BICUTAN 2",
    "VENICE MCKINLEY",
    "WEST BICUTAN 1",
  ],
  A114: [
    "Aguirre",
    "Alabang highway",
    "Bayanan 2",
    "Bf homes 1",
    "BF homes 2",
    "Canaynay",
    "Cupang",
    "Dasa san dionisio",
    "Dasa san Isidro",
    "Evacom",
    "FESTIVAL MALL",
    "Fourth Estate",
    "Jaka",
    "LC Montillano",
    "Lianas mall Alabang",
    "Lianas mall Sucat",
    "Lirag AGUIRRE",
    "Lopez",
    "Madison",
    "Maywood",
    "Multinational",
    "Muntinlupa",
    "Muntinlupa market",
    "Putatan",
    "San Antonio Valley 1",
    "San Antonio Valley 2",
    "San Guillermo",
    "Sandionisio Dasa",
    "Soldiers hills",
    "South Park ayala",
    "South Station",
    "Sto niño",
    "SUCAT 4",
    "Sucat 5",
    "Sucat Road",
    "Teoville Sucat",
    "Vista mall lakefront",
    "Walter Mart Muntinlupa",
    "Zentrum sucat",
  ],
  A117: [
    "ANONAS",
    "BAGO BANTAY",
    "BALINTAWAK PUREGOLD",
    "BANLAT",
    "CENTRIS",
    "CIRCLE C",
    "CONGRESSIONNAL",
    "DEL MONTE",
    "EAST AVE V LUNA",
    "EDSA KAMUNING",
    "FISHERSMALL",
    "FRISCO 2",
    "FRISCO 3",
    "GSIS",
    "KAINGIN",
    "KAMIAS",
    "KAMUNING",
    "LL TERRAZZO",
    "MASIGLA",
    "MINDANAO",
    "MATALINO",
    "MUNUZ",
    "PAG ASA",
    "PANAY",
    "PARAMOUNT 1",
    "PARAMOUNT 2",
    "PHILAND",
    "Q MART",
    "QUEDSA PLASA",
    "RMR",
    "ROAD 3",
    "ROCES",
    "ROOSEVELT",
    "ROTC HEANTER",
    "SCT.BORROMEO",
    "SHORTHORN",
    "SIKATUNA",
    "TANDANG SORA",
    "TATALON",
    "TEACHERS VILLEGE",
    "LTO BR",
    "VETERANCE",
    "VERTIS MALL",
    "VISAYAS",
    "WEST AVE",
    "WILCON",
  ],
  A301: [
    "CLH BALIBAGO 2",
    "CLH BALIBAGO COMPLEX",
    "CLH BALIBAGO HIWAY",
    "CLH BIÑAN 1",
    "CLH BIÑAN 2",
    "CLH BIÑAN 3",
    "CLH BIÑAN LC",
    "CLH BULIHAN 1",
    "CLH BULIHAN 2",
    "CLH CABUYAO 1",
    "CLH CABUYAO 2",
    "CLH CALENDOLA",
    "CLH CARMONA",
    "CLH CHRYSANTHEMUM",
    "CLH DITA",
    "CLH GOLDEN CITY",
    "CLH HALANG",
    "CLH KATAPATAN",
    "CLH LAG 1",
    "CLH LAG 2",
    "CLH LANDAYAN",
    "CLH MABINI",
    "CLH MABUHAY",
    "CLH MADERAN",
    "CLH MAGUYAM",
    "CLH MAMATID",
    "CLH PACITA 1",
    "CLH PACITA 2",
    "CLH PHASE 2A",
    "CLH PLATERO",
    "CLH PROPER MAGRA",
    "CLH PULIDO",
    "CLH PULO",
    "CLH PULONG STA CRUZ",
    "CLH PUTING KAHOY",
    "CLH RIVERSIDE",
    "CLH ROBINSON",
    "CLH SAN FRANCISCO",
    "CLH SAN JOSE",
    "CLH SOUTH CITY",
    "CLH SP 1",
    "CLH SP 2",
    "CLH STA ROSA 1",
    "CLH STA ROSA 2",
    "CLH TIMBAO",
  ],
  A303: [
    "ADVINCULA",
    "AMAYA",
    "BAYANAN",
    "BIGA",
    "BINAKAYAN",
    "BUCANDALA EXT",
    "BUHAY NA TUBIG",
    "BURGOS",
    "CAMELLIA",
    "CELESTINO",
    "DISTRICT MALL",
    "GREEN VALLEY",
    "IMUS 1",
    "IMUS 2",
    "LC2 BACOOR",
    "LOKAL MALL",
    "MACARIA",
    "MALAGASANG",
    "MARAGONDON",
    "MILLENNIUM",
    "MOLINO 3",
    "MOLINO 4",
    "NAIC IBAYO",
    "NAIC POBLETE",
    "NAIC SAN ROQUE",
    "NAIC SORIANO",
    "NIOG",
    "NOVELETA",
    "PAG ASA 1",
    "PAG ASA 2",
    "PALICO",
    "PARADAHAN",
    "PATERNO",
    "PERPETUAL",
    "ROBINSON MALL",
    "RONQUILLO",
    "ROSARIO",
    "SALAWAG 1",
    "SALAWAG 2",
    "TANZA 1",
    "TANZA 2",
    "TEJERO",
    "TERMINUS",
    "TIRONA",
  ],
  A304: [
    "CLH ALFONSO MAIN",
    "CLH AMADEO",
    "CLH BAILEN",
    "CLH CITYMALL IMUS",
    "CLH CONGRESSIONAL",
    "CLH DASMA 1",
    "CLH DASMA 2",
    "CLH DASMA 5",
    "CLH DBB-C",
    "CLH DBB-E",
    "CLH DELA SALLE",
    "CLH DISTRICT MALL",
    "CLH GENERAL TRIAS",
    "CLH GOLDEN CITY",
    "CLH GREEN GATE",
    "CLH HUGO PEREZ",
    "CLH INDANG 1",
    "CLH INDANG 2",
    "CLH KADIWA",
    "CLH LANGKAAN",
    "CLH LUCIANO",
    "CLH LUKSUHIN",
    "CLH LUZVIMINDA",
    "CLH MANGGAHAN ext.",
    "CLH MANGGAHAN main",
    "CLH MENDEZ",
    "CLH OLIVARES",
    "CLH PALA PALA",
    "CLH PALIPARAN (NEW)",
    "CLH PREMIER",
    "CLH PUREGOLD ANABU",
    "CLH ROBINSON IMUS",
    "CLH SALITRAN",
    "CLH SALITRAN AGUINALDO",
    "CLH SILANG 1",
    "CLH SILANG EXT",
    "CLH SUNNY BROOKE",
    "CLH TAGAYTAY 1",
    "CLH TAGAYTAY 2",
    "CLH TRECE ext.",
    "CLH TRECE main",
    "CLH UNITOP",
    "CLH-PALIPARAN",
  ],
  A305: [
    "Agoncillo",
    "Balayan 1",
    "Balayan 2",
    "Batangas 2",
    "Batangas 3",
    "Batangas 4",
    "Batangas 5",
    "Batangas 6",
    "Bauan 1",
    "Bauan 2",
    "Bauan 3",
    "Bauan 4",
    "Calaca",
    "Calatagan",
    "Calicanto Batangas City",
    "Calzada, Balayan",
    "CLRB Calatagan",
    "CLRB Savemore Nasugbu",
    "Cuenca",
    "Dacanlao",
    "Dominador, Alitagtag",
    "Kumintang, Batangas",
    "Lemery 1",
    "Lemery 2",
    "Lemery 3",
    "Lemery 4",
    "Lemery 5",
    "Lian",
    "Lian Martires",
    "Lucsuhin",
    "Mabini",
    "Manghinao Proper",
    "Muzon, Alitagtag",
    "Nasugbu 1",
    "Nasugbu 2",
    "Palico, Tuy",
    "Pallocan West, Batangas",
    "San Jose",
    "San Luis",
    "San Pascual 1",
    "San Pascual 2",
    "San Roque",
    "Taal",
    "Tanagan",
    "Tawilisan",
    "Tuy",
  ],
  A306: [
    "CLH ABR DI ELOG",
    "CLH BANAY BANAY LIPA CITY",
    "CLH BANSUD",
    "CLH BARCENAGA",
    "CLH BONGBONG",
    "CLH GLORIA",
    "CLH IBAAN",
    "CLH ILAYA",
    "CLH LIBORO 1",
    "CLH LIBORO 2",
    "CLH LIMA MALVAR",
    "CLH LIPA1",
    "CLH LIPA2",
    "CLH LIPA4",
    "CLH LIPA5",
    "CLH MAGSAYSAY",
    "CLH MALVAR",
    "CLH MAMBORAO 1",
    "CLH MAMBURAO 2",
    "CLH MANSALAY",
    "CLH MATAAS NA KAHOY",
    "CLH MDO MAIN",
    "CLH MINDORO 1",
    "CLH MINDORO 2",
    "CLH PADRE GARCIA",
    "CLH PALUAN",
    "CLH PINAMALAYAN 1",
    "CLH Pinamalayan 2",
    "CLH PUERTO POBLACION",
    "CLH PUERTO WHITE BEACH",
    "CLH ROSARIO1",
    "CLH ROSARIO2",
    "CLH ROXAS",
    "CLH ROXAS DRIVE",
    "CLH SABLAYAN",
    "CLH SACORRO",
    "CLH SAN ANTONIO",
    "CLH SAN JUAN1",
    "CLH SAN JUAN2",
    "CLH STA CRUZ",
    "CLH TAYSAN",
    "CLH VICTORIA",
  ],
  A403: [
    "BAJAC",
    "BANTAYAN ISLAND",
    "BOGO1",
    "BOGO2",
    "BORBON",
    "CAMOTES",
    "CARMEN",
    "CATMON",
    "CATMON DAAN",
    "CAWIT",
    "CITY MALL",
    "COMPOSTELA",
    "CONSOLACION",
    "CONSOLACION2",
    "CONSOLACION3",
    "COTCOT",
    "CPM",
    "DAAN BANTAYAN",
    "DANAO1",
    "DANAO2",
    "ESPERANZA",
    "GRANDMALL",
    "HAGNAYA",
    "HIWAY LILOAN",
    "ILIHAN",
    "KAWIT",
    "LILOAN",
    "MADRIDEJOS",
    "MALINAO",
    "MAYA",
    "MEDELLIN",
    "MITSUMI",
    "NORTHERN",
    "PITOGO",
    "POB COMPOSTELA",
    "POB.TUBURAN",
    "PORO",
    "PRINCE TOWN",
    "PROPER YATI",
    "SAN REMIGIO",
    "SOGOD",
    "STA FE",
    "TABOGON",
    "TABUELAN",
    "TAYTAYAN",
    "TAYUD CONSOLACION",
    "TAYUD LILOAN",
    "TICAD",
    "TUBURAN",
    "TUDELA",
    "YATI",
  ],
  A406: [
    "ABUYOG",
    "ABUYOG TERMINAL",
    "ALANGALANG",
    "ALMERIA",
    "ANAHAWAN",
    "BABATNGON",
    "BALANGIGA",
    "BARUGO",
    "BASEY SAMAR",
    "BILIRAN BILIRAN",
    "BURAUEN",
    "CABUCGAYAN",
    "CAIBIRAN",
    "CAPOOCAN",
    "CARIGARA",
    "CARIGARA REAL",
    "CLH-NAVAL",
    "CULABA",
    "DAGAMI",
    "DULAG",
    "DULAG HIGHWAY",
    "GAISANO REAL",
    "GIPORLOS",
    "GUIUAN 1",
    "GUIUAN 2",
    "HINUNANGAN",
    "HINUNANGAN TERMINAL",
    "HINUNDAYAN",
    "JARO LEYTE",
    "JAVIER",
    "KAWAYAN",
    "LA PAZ LEYTE",
    "LACTASON",
    "LAWAAN",
    "LEMON CROSSING",
    "LEYTE LEYTE",
    "MACARTHUR E SAMAR",
    "MACARTHUR LEYTE",
    "MARASBARAS",
    "MARIPIPI",
    "MAYORGA",
    "NAGANAGA",
    "NAVAL 2",
    "NAVAL MARKET",
    "PALO 2",
    "PAWING",
    "PICAS SAGKAHAN",
    "PRINCE NAVAL",
    "QUINAPONDAN",
    "ROBINSONS NORTH ABUCAY",
    "ROBINSONS PLACE TACLOBAN",
    "SAGCAHAN",
    "SAINT BERNARD",
    "SALCEDO",
    "SAN JUAN",
    "SAN MIGUEL",
    "SILAGO",
    "STA FE LEYTE",
    "TACLOBAN 1",
    "TACLOBAN 4",
    "TACLOBAN 5",
    "TACLOBAN JUSTICE",
    "TACLOBAN MAIN",
    "TACLOBAN SAN JOSE",
    "TANAUAN",
    "TANAUAN HIGH WAY",
    "TUNGA",
    "V&G TALIPAPA",
  ],
  A407: [
    "CLH ALBUERA",
    "CLH BATO",
    "CLH BAYBAY - 1",
    "CLH BAYBAY - 2",
    "CLH BAYBAY CENTRAL",
    "CLH BAYBAY CENTRAL GRS",
    "CLH BONTOC MARKET",
    "CLH CALUBI-AN",
    "CLH COGON ROTUNDA",
    "CLH HILONGOS - 1",
    "CLH HILONGOS EASTERN",
    "CLH HINDANG",
    "CLH ICHON",
    "CLH INOPACAN",
    "CLH ISABEL",
    "CLH KANANGA - 1",
    "CLH KANANGA HIGHWAY",
    "CLH LIBAGON",
    "CLH LILOAN",
    "CLH LINAO",
    "CLH MAASIN - 1",
    "CLH MAASIN - 2",
    "CLH MAASIN - 2 GRS",
    "CLH MAASIN SJC",
    "CLH MAHAPLAG",
    "CLH MAHARLIKA LILOAN",
    "CLH MALITBOG",
    "CLH MATAG-OB",
    "CLH MATALOM",
    "CLH MERIDA",
    "CLH ORMOC - 1",
    "CLH ORMOC - 2",
    "CLH ORMOC - 2 GRS",
    "CLH PADRE BURGOS",
    "CLH PALOMPON",
    "CLH PALOMPON P.I.T",
    "CLH PINTUYAN",
    "CLH R. KANGLEON",
    "CLH ROBINSON",
    "CLH ROBINSON ORMOC GRS",
    "CLH SABANG",
    "CLH SAN FRANCISCO",
    "CLH SAN ISEDRO",
    "CLH SANVIDAL",
    "CLH SIMANGAN",
    "CLH SOGOD",
    "CLH SOGOD GRS",
    "CLH SOGOD TERMINALT",
    "CLH STO. NINO ISABEL",
    "CLH TABANGO",
    "CLH TOMAS UPPOS",
    "CLH UWAK",
    "CLH V.S.U",
    "CLH VALENCIA",
    "CLH VILLABA",
    "VILLABA GRS",
    "VILLABA MARKET",
  ],
  A408: [
    "Akishola",
    "Alijis Greenplains",
    "Araneta",
    "Astral",
    "Bacolod Main",
    "Banago",
    "Bata",
    "Burgos East",
    "Celin",
    "City Hall",
    "Felisa",
    "Gatuslao",
    "Granada",
    "Handumanan",
    "Hilado",
    "Home Site",
    "Just Jewel SM Mall",
    "Lacson 1",
    "Lacson L fisher",
    "Libertad Extension",
    "Mabini",
    "Mandalagan",
    "Mansilingan 1",
    "Mansilingan h way",
    "Murcia 1",
    "Pana ad",
    "Riverside",
    "San Sebastian",
    "Singcang",
    "Sta Clara",
    "Stop light",
    "Sum Ag 1",
    "Sum ag PM",
    "Sum ag San Juan",
    "Talisay 1",
    "Talisay 2",
    "Talisay Concepcion",
    "Talisay TUP",
    "Tangub",
    "Villamonte",
  ],
  A412: [
    "CLH BASAY BRANCH",
    "CLH BAYAWAN 1 TINAGO BRANCH",
    "CLH BINALBAGAN 1",
    "CLH BINALBAGAN 2",
    "CLH BINALBAGAN JLL",
    "CLH BONAWON BRANCH",
    "CLH BRGY 9, KABANKALAN",
    "CLH BRGY. SUBA BAYAWAN",
    "CLH BURGOS SANTA CATALINA",
    "CLH CANDONI BRANCH",
    "CLH CAUAYAN",
    "CLH CM RECTO BAYAWAN BRANCH",
    "CLH DANCALAN",
    "CLH HIMAMAYLAN BRANCH 1",
    "CLH HIMAMAYLAN BRANCH 2",
    "CLH HINIGARAN 1",
    "CLH HINIGARAN BRANCH 2",
    "CLH HINOBA-AN BRANCH 1",
    "CLH HINOBA-AN BRANCH 2",
    "CLH ILOG PROPER",
    "CLH INAYAWAN",
    "CLH ISABELA BRANCH",
    "CLH ISABELA PLAZA BRANCH",
    "CLH KABANKALAN 2",
    "CLH KABANKALAN 3",
    "CLH KABANKALAN BRANCH 1",
    "CLH KABANKALAN GUANZON",
    "CLH KABANKALAN PLAZA BRANCH",
    "CLH MABINAY LUMBANGAN",
    "CLH MABINAY PROPER",
    "CLH MALOH BRANCH",
    "CLH POBLACION BAYAWAN BRANCH",
    "CLH PONTEVEDRA BRANCH 1",
    "CLH PONTEVEDRA HIGHWAY BRANCH",
    "CLH SANTA CATALINA",
    "CLH SIATON BRANCH",
    "CLH SIPALAY BRANCH 1",
    "CLH SIPALAY BRANCH 2",
    "CLH SU-AY HIMAMAYLAN BRANCH",
    "CLH ZAMBOANGUITA BRANCH",
  ],
  A413: [
    "CLH AROROY 1",
    "CLH AROROY SAN JOSE",
    "CLH BALENO",
    "CLH BALUD",
    "CLH BATUAN",
    "CLH CABITAN",
    "CLH CATAINGAN CROSING",
    "CLH CAWAYAN DIVISORIA",
    "CLH CAWAYAN POBLACION",
    "CLH CLAVERIA",
    "CLH CLH CATAINGAN MAIN",
    "CLH CROSING MASBATE",
    "CLH DIMASALANG",
    "CLH ESPERANZA",
    "CLH GAISANO",
    "CLH JONES",
    "CLH MABATE 3",
    "CLH MALINTA",
    "CLH MANDAON",
    "CLH MASBATE 1",
    "CLH MASBATE 2",
    "CLH MASBATE 4",
    "CLH MASBATE 5",
    "CLH MILAGROS 1",
    "CLH MOBO",
    "CLH MONREAL",
    "CLH PALANAS",
    "CLH PIO V. CORPUZ",
    "CLH PLACER 1",
    "CLH PLACER KATIPUNAN",
    "CLH PLACER MAIN",
    "CLH POBLACION EAST",
    "CLH SAN FERNANDO",
    "CLH SAN JACINTO",
    "CLH TARA",
    "CLH UMABAY",
    "CLH USON",
    "CLH ZURBITO",
  ],
  A414: [
    "CLH ALEGRIA",
    "CLH ALLEN",
    "CLH ARTECHE",
    "CLH AWANG CALBAYOG",
    "CLH BALANGKAYAN",
    "CLH BORONGAN 1",
    "CLH BORONGAN 2",
    "CLH BORONGAN 3",
    "CLH BURAY",
    "CLH CALBAYOG 1",
    "CLH CALBAYOG 2",
    "CLH CALBAYOG 3",
    "CLH CALBAYOG MAGSAYSAY 4",
    "CLH CALBIGA",
    "CLH CAN - AVID",
    "CLH CANLAPWAS CATBALOGAN",
    "CLH CAPOOCAN CALBAYOG",
    "CLH CATARMAN 1",
    "CLH CATARMAN 2",
    "CLH CATARMAN JP RIZAL",
    "CLH CATBALOGAN 1",
    "CLH CATBALOGAN 2",
    "CLH CATBALOGAN 3",
    "CLH CATUBIG",
    "CLH CAWAYAN CATARMAN",
    "CLH DALAKIT CATARMAN",
    "CLH DOLORES MAIN",
    "CLH DOLORES REAL",
    "CLH GAMAY",
    "CLH GANDADARA",
    "CLH HINABANGAN",
    "CLH JIABONG",
    "CLH LAVESAREZ",
    "CLH LLORENTE",
    "CLH LOA-ANG",
    "CLH LOPE DE VEGA",
    "CLH MAULONG",
    "CLH MAYDOLONG",
    "CLH MONDRAGON",
    "CLH OQUENDO",
    "CLH ORAS",
    "CLH PAGSANGHAN",
    "CLH PAMBUJAN",
    "CLH PATAG CATBALOGAN",
    "CLH PINABACDAO",
    "CLH RAWIS",
    "CLH SAN JORGE",
    "CLH SAN JOSE",
    "CLH SAN JULIAN",
    "CLH SAN POLICARPO",
    "CLH SAN ROQUE",
    "CLH SONGCO BORONGAN",
    "CLH STA MARGARITA",
    "CLH SULAT",
    "CLH TAFT",
    "CLH TARANGNAN",
    "CLH WARD 2 SAN ANTONIO",
  ],
  A420: [
    "CLH AYUNGON",
    "CLH BAGO 1",
    "CLH BAGO PM",
    "CLH BINDOY",
    "CLH CADIZ VETERANCE",
    "CLH CALATRAVA",
    "CLH CANLAON",
    "CLH EB MAGALONA",
    "CLH ESCALANTE",
    "CLH ESCALANTE PM",
    "CLH GUIHULNGAN",
    "CLH GUIHULNGAN OSMEñA",
    "CLH JIMALALUD",
    "CLH LA CARLOTA 1",
    "CLH LA CARLOTA 2",
    "CLH LA CARLOTA PM",
    "CLH LA CASTILLANA 1",
    "CLH LA CASTILLANA FERIA",
    "CLH LA LIBERTAD",
    "CLH MANAPLA",
    "CLH MANJUYOD",
    "CLH MOISES PADILLA",
    "CLH OLD SAGAY",
    "CLH SAGAY 1",
    "CLH SAGAY PARAISO",
    "CLH SAGAY ROXAS AVENUE",
    "CLH SAN CARLOS",
    "CLH SAN CARLOS PM",
    "CLH SAN ENRIQUE",
    "CLH SILAY",
    "CLH SILAY HI-WAY",
    "CLH TAYASAN",
    "CLH TOBOSO",
    "CLH VALEHERMOSO",
    "CLH VALLADOLID",
    "CLH VICTORIAS 1",
    "CLH VICTORIAS PM",
  ],
};

export const BRANCH_OPTIONS = Array.from(
  new Set(Object.values(AREA_BRANCH_OPTIONS).flat())
).sort((a, b) => a.localeCompare(b));

const BRANCH_INDEX = new Map(BRANCH_OPTIONS.map((branch, index) => [branch, index]));

export function sortBranches(values) {
  return [...values].sort((a, b) => {
    const aIndex = BRANCH_INDEX.has(a) ? BRANCH_INDEX.get(a) : Number.MAX_SAFE_INTEGER;
    const bIndex = BRANCH_INDEX.has(b) ? BRANCH_INDEX.get(b) : Number.MAX_SAFE_INTEGER;

    if (aIndex !== bIndex) return aIndex - bIndex;
    return String(a).localeCompare(String(b));
  });
}

export function getBranchesForArea(area) {
  return sortBranches(AREA_BRANCH_OPTIONS[area] ?? []);
}
